"""Forecast-model construction, wrappers, baselines, and registries."""

from .augmentations import CovariateAugmentation, RepeatConstantOutput, normalize_covariates
from .baselines import (
    ExpectedBaseline,
    LinearBaseline,
    LookbackBaseline,
    PeriodicLinearBaseline,
    PersistenceBaseline,
    RepeatBaseline,
)
from .forecast import (
    FOUNDATION_MODEL_ALIASES,
    ModelConfig,
    TimeTensorModel,
    build_model_from_config,
    load_model,
)
from proposal.grevin import GRevIN, build_grevin_normalization
from proposal.normalizations import (
    IdentityNormalization,
    InstanceMinMaxNormalization,
    MinMaxNormalization,
    RMSNormalization,
    RelativeMeanNormalization,
    RevIN,
    SigmoidNormalization,
    StandardNormalization,
    TanhNormalization,
    build_normalization,
    denormalize_standard,
    get_minmax_stats,
    get_normal_stats,
    get_rms_stats,
    normalize_standard,
)
from .sklinear import SkLinearForecaster, iter_loader_xy
from external_models import (
    Chronos2,
    ChronosBolt,
    ChronosT5,
    DLinear,
    PatchTST,
    TSICLForecaster,
)

__all__ = [
    "FOUNDATION_MODEL_ALIASES",
    "Chronos2",
    "ChronosBolt",
    "ChronosT5",
    "CovariateAugmentation",
    "DLinear",
    "ExpectedBaseline",
    "GRevIN",
    "IdentityNormalization",
    "InstanceMinMaxNormalization",
    "LinearBaseline",
    "LookbackBaseline",
    "MinMaxNormalization",
    "ModelConfig",
    "PatchTST",
    "PeriodicLinearBaseline",
    "PersistenceBaseline",
    "RMSNormalization",
    "RelativeMeanNormalization",
    "RepeatBaseline",
    "RepeatConstantOutput",
    "RevIN",
    "SigmoidNormalization",
    "SkLinearForecaster",
    "StandardNormalization",
    "TanhNormalization",
    "TSICLForecaster",
    "TimeTensorModel",
    "build_model_from_config",
    "build_grevin_normalization",
    "build_normalization",
    "denormalize_standard",
    "get_minmax_stats",
    "get_normal_stats",
    "get_rms_stats",
    "iter_loader_xy",
    "load_model",
    "normalize_covariates",
    "normalize_standard",
]
